site_name: Hybrid Cloud Technology for E-Delivery
site_url: https://https://jor-donegal.github.io/PGDip-HCT/
theme:
  name: readthedocs
  logo: images/DeathStar.jpg

copyright: Copyright © 2026, John O'Raw

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.detailssite_name: Program Template
site_url: https://example.com
theme:
  name: readthedocs
  logo: images/DeathStar.jpg

copyright: Copyright © 2026, John O'Raw

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details