site_name: Hybrid Cloud Technology for E-Delivery
site_url: https://example.com
theme:
  logo: images/DeathStar.jpg
  name: readthedocs
  palette:
    scheme: default
    primary: yellow
    accent: deep purple

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

copyright: Copyright Â© 2026, John O'Raw